import BestSeller from '@/features/products/organisms/best-seller';
import LatestCollection from '@/features/products/organisms/latest-collection';
import Hero from '@/shared/components/atoms/hero';
import NewsLetter from '@/shared/components/atoms/newsletter';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Bootik',
  description: 'Generated by create next app',
};

export default function Home() {
  return (
    <>
      <Hero/>
      <LatestCollection/>
      <BestSeller/>
      <NewsLetter/>
    </>
  );
}
