import { Button } from '@/components/ui/button';
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import CalendarDateRangePicker from '@/components/ui/calendar-date-range-picker';
import type { Metadata } from 'next';
import Overview from './dashboard/overview';

export const metadata: Metadata = {
  title: 'Admin',
  description: 'Generated by create next app',
};

export default function AdminPage() {
  return (
    <div>
      <Overview />
    </div>
  );
}
