import ProductInfo from "@/features/products/components/molecules/product-info";
import { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: 'Bootik',
  description: 'Generated by create next app',
};

const Page = ({ params }: { params: { productId: string } }) => {
  const { productId } = React.use(params);

  return (
    <>
     <ProductInfo productId={productId}/>
    </>
  );
}
export default Page;