import Cart from '@/features/cart/organisms/cart';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Cart',
  description: 'Generated by create next app',
};

export default function Page() {
  return (
    <>
      <Cart/>  
    </>
  );
}
